use_frameworks!

platform :ios, '8.0'

target 'NormalTools_Example' do
  pod 'NormalTools', :path => '../'

  target 'NormalTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
