use_frameworks!

platform :ios, '9.0'

target 'NormalTools_Example' do
  pod 'NormalTools', :path => '../'

  target 'NormalTools_Tests' do
    inherit! :search_paths
    pod 'YYCategories', '~> 1.0.4'
    pod 'FBSnapshotTestCase'
  end
end
